Namespaces and topics specified as parameters.
strands-project/strands_perception_people pull request #218
Opened 2018-04-18 13:38 UTC by MFernandezCarmona

Also some other minor changes:
people_tracker_filter/src/filter.cpp: changed method to acknowledge map reception. 
upper_body_detector: merged with ENRICHME branch, solves most of the memory problems.

2018-04-18 20:14 UTC, marc-hanheide commented
can you check why this failed? See https://lcas.lincoln.ac.uk/buildfarm/job/Kpr__strands_perception_people__ubuntu_xenial_amd64/2/console

This is the problem:

```
15:11:34 CMake Error at CMakeLists.txt:2 (project):
15:11:34   The CMAKE_C_COMPILER:
15:11:34 
15:11:34     /usr/lib/ccache/cc
15:11:34 
15:11:34   is not a full path to an existing compiler tool.
15:11:34 
15:11:34   Tell CMake where to find the compiler by setting either the environment
15:11:34   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
15:11:34   the compiler, or to the compiler name if it is in the PATH.
15:11:34 
15:11:34 
15:11:34 CMake Error at CMakeLists.txt:2 (project):
15:11:34   The CMAKE_CXX_COMPILER:
15:11:34 
15:11:34     /usr/lib/ccache/c++
15:11:34 
15:11:34   is not a full path to an existing compiler tool.
15:11:34 
15:11:34   Tell CMake where to find the compiler by setting either the environment
15:11:34   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
15:11:34   to the compiler, or to the compiler name if it is in the PATH.
```

I recall a similar problem where the ROS dependencies have changes and one now needs to explicitly depend on roscpp or similar, I seem to recall.

2018-04-19 07:24 UTC, lucasb-eyer requested changes
Overall, I think these are great changes that make the detector much better. I commend you for going through that code and thanks a lot for contributing back :+1: :smile:

I left a few comments inline I'd like you to address, after that I think we can merge. From the diff, I don't see how it can cause the build failure (it can't find a compiler).

One more thing is, if I understand correctly, this could also make it work with Kinect v2, right? It would be great if you could add a section to the README with describing this and how to use it (basically just using the new config, but that's way not obvious for users who don't dig through the code like you did).

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/KConnectedComponentLabeler.cpp
> +                trueLabelArray.clear();
Not needed, but doesn't hurt either.

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/KConnectedComponentLabeler.cpp
> +	//regionArea = NULL;
You can remove the comments, git keeps history :smile:

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/KConnectedComponentLabeler.cpp
> +	//regionLabel = NULL;
same here

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/KConnectedComponentLabeler.cpp
> +        regionLabel.clear();
No need for `.clear()` as they get deleted when going out of scope here.

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/detector.cpp
> +                   ROS_INFO("upper_body_detector: compute freespace - pos_x:%i/%i, pos_z:%i/%i - out of range!", pos_x,x_bins,pos_z,z_bins);
Oh, that happened sometimes? Good catch, if so!

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/detector.cpp
> +            occ_map_binary(x,y) = (occ_map(x,y) < Globals::freespace_threshold) ? 0 : 1;
It would be nice if you could rename `y` to `z`, as that's consistent with nomenclature elsewhere in the detector.

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/main.cpp
> +        for (int c = 0;c < info->width;c++) {
Yes, finally, thank you :smile:

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/main.cpp
> +            }
This block of code has several problems:

1) the second check is checking for NaNs, right? In the original code, NaNs were passed through, but with your change, they are converted to 0s. I think NaNs should still be passed through, as they signify something completely different from depth 0.

2) Interpreting the pixel type using DEPTH_SCALE sounds scary for me, imagine someone changes DEPTH_SCALE to 0.999 and everything breaks, no way they will understand why.

3) I'm not sure what value is used for NaN in the `ushort`, i.e. original encoding? But it should be converted to `NaN`, too. I'm assuming it's `0` in the following, but please do double-check to make sure.

I suggest something like the following (untested):

```
    int inttype = img_depth_.type();
    uchar type = inttype & CV_MAT_DEPTH_MASK;
    if (type == CV_32F) {
        matrix_depth(c, r) = img_depth_.at<float>(r,c) / Globals::DEPTH_SCALE;
    } else if (type == CV_16U) {
        float raw_val = img_depth_.at<ushort>(r,c);
        if (raw_val == 0) { // Please double-check if 0 corresponds to NaN.
            matrix_depth(c, r) = nanf();
        } else {
            matrix_depth(c, r) = raw_val / Globals::DEPTH_SCALE;
        }
    } else {
        ROS_ERROR("Unknown depth-map type, no detections.");
    }
```

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/src/main.cpp
> +    cv_color_ptr->image = image;
This might have worked by chance, but this really doesn't look like correct code. Why not just `cv_color_ptr = cv_bridge::toCvCopy(image);` (note: `image`, not `color`.)

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/include/detector.h
> +    bool visualize_roi=false;
This effectively makes it C++11, which would be nice to avoid. It's not crucial, but it's a simple thing here.

2018-04-19 07:24 UTC, lucasb-eyer commented on upper_body_detector/config/upper_body_detector.yaml
> +    min_height: 0.85
I'm not sure it's a good idea to change these in the default file.
Knowing Dennis, he probably spent quite some time tuning them for his scenarios, and you tuned them for your scenarios.

I'd be very happy if you would leave the original parameters, make a new copy with your parameters (like you did with the `r2`), and then in the README quickly describe how to use them (and what scenario your parameters were tuned for).

2018-04-19 07:24 UTC, lucasb-eyer commented on ground_plane_estimation/src/fixed_gp.cpp
> +    gp.header.stamp = ros::Time::now();
Why the change? I think we've been careful to "pull through" the timestamps where needed, for example, the depth map's stamp gets pulled through the detector and tracker. So you need a good argument for the change here.

2018-04-19 11:01 UTC, MFernandezCarmona commented on upper_body_detector/src/main.cpp
> +            }
Hi,
The real human perception expert in ENRICHME was @scosar. I will check this with him later. In the meantime your solution seems more robust.

2018-04-19 11:08 UTC, MFernandezCarmona commented
Hi,
Our fork was really maintained by @scosar. I will talk with him about your comments and corrections. I did use this with Kinect2, I will put more detailled description and probably an extra launcher later.
Cheers

2018-04-19 17:27 UTC, marc-hanheide commented
retest this please

2018-04-20 07:37 UTC, marc-hanheide commented
@MFernandezCarmona I managed to fix the issues around `ccache` on the integration server, but there as indeed relevant issues still to be resolve, see https://lcas.lincoln.ac.uk/buildfarm/job/Kpr__strands_perception_people__ubuntu_xenial_amd64/12/console

```
18:32:10 [ 40%] Building CXX object CMakeFiles/upper_body_detector.dir/src/main.cpp.o
18:32:17 /tmp/catkin_workspace/src/strands_perception_people/upper_body_detector/src/main.cpp: In function ‘void callback(const ImageConstPtr&, const ImageConstPtr&, const ConstPtr&, const CameraInfoConstPtr&)’:
18:32:17 /tmp/catkin_workspace/src/strands_perception_people/upper_body_detector/src/main.cpp:294:33: error: too few arguments to function ‘float nanf(const char*)’
18:32:17        matrix_depth(c, r) = nanf();
18:32:17                                  ^
18:32:17 In file included from /usr/include/math.h:104:0,
18:32:17                  from /usr/include/c++/5/cmath:44,
18:32:17                  from /opt/ros/kinetic/include/ros/time.h:55,
18:32:17                  from /opt/ros/kinetic/include/ros/ros.h:38,
18:32:17                  from /tmp/catkin_workspace/src/strands_perception_people/upper_body_detector/src/main.cpp:2:
18:32:17 /usr/include/x86_64-linux-gnu/bits/mathcalls.h:228:14: note: declared here
18:32:17  __MATHCALLX (nan,, (const char *__tagb), (__const__));

```

2018-04-20 12:55 UTC, lucasb-eyer commented
Thanks for adressing all these, and thanks again for merging back upstream!

The build failure is because I forgot that `nanf()` needs to be called as `nanf("")` instead, that should fix it.

2018-04-30 09:01 UTC, merged